### ISSUE TITLE
testoverride not work in cloud mode?

### ISSUE THREAD

**Issue by z7701858** [coreruleset/go-ftw#147]
.ftw.yaml
```
logfile: 
logmarkerheadername: 
mode: "cloud"
testoverride:
  input:
    dest_addr: "testphp.vulnweb.com"
    port: 80
    protocol: "http"
```
`go-ftw run --cloud --debug`
```
🛠️  Starting tests!
🚀 Running go-ftw!
👉 executing tests in file 911100.yaml
        running 911100-1: 8:45AM DBG ftw/http: sending data:
GET / HTTP/1.1
Accept: text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5
Connection: close
Host: localhost
User-Agent: OWASP CRS test agent



8:45AM DBG ftw/run: error receiving response: unexpected EOF

Error: failed sending request to destination &{DestAddr:testphp.vulnweb.com Port:80 Protocol:http}: unexpected EOF
```

**Comment by theseion** [comment]
The error message is correct but misleading. The issue is that your `Host` header doesn't match the endpoint. You have two tools at you disposal to fix that:

- `override_empty_host_header`: if the host header is empty you can override it with a default
- `headers`: override the test headers

Below is an example that I've tested.

```yaml
logfile:
logmarkerheadername:
mode: "cloud"
testoverride:
  input:
    override_empty_host_header: true
    dest_addr: "testphp.vulnweb.com"
    port: 80
    protocol: "http"
    headers:
        - Host: "testphp.vulnweb.com"
```
