### ISSUE TITLE
Allow precise configuration of raw request body

### ISSUE THREAD

**Issue by theseion** [coreruleset/go-ftw#205]
The following body represents a chunk in a `Transfer-Encoding: chunked` request (content length, content, remaining chunks):

```yaml
data: |
  7
  foo=bar
  0
```

While the contents of the lines is readable, the line breaks are not, but are relevant to the request, as the specification requires each line to be terminated with `\r\n`. In this particular context it is also not possible to properly encode the line breaks.

One idea to get around this limitation is to provide a "line specification", like so:

```yaml
raw_lines:
  - content: 7
    ending: "\r\n"
  - content: "foo=bar"
    ending: "\r\n"
  - content: 0
    ending: "\r\n"
```
This format would give us more control and better readability, in addition to sending malformed request bodies.
