### ISSUE TITLE
Marker requests' `Host` header is always "localhost" 

### ISSUE THREAD

**Issue by airween** [coreruleset/go-ftw#361]
I want to test a custom rule set with a specific pre-configured vhost, which listens on localhost (127.0.0.1).

I added `Host` header to each test, eg:
```yaml
          headers:
            User-Agent: "OWASP CRS test agent"
            Host: "my.vhost.com"
            Accept: text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5
            Content-Type: "application/xml"
```

The **test** request is sent with the specified header, but when `go-ftw` sends the marker requests before and after it, they has "localhost".

So the markers' logs are written to the original log, but the test result is written into the vhost's own log (if there is).

It would be nice if the marker requests also use the `Host` header like the test itself.

Workaround: use the same error.log for specific vhost as the default.
