### ISSUE TITLE
Cannot set host header

### ISSUE THREAD

**Issue by usp-ast** [coreruleset/go-ftw#453]
Experimentally was not possible to set the `Host` header, neither via config file nor via yaml test files, was always using `Host: localhost`.

- `ftw_1.2.0_amd64.deb` (on Ubuntu 22.04)
- Settings `dest_addr` and `port` in config file did work, i.e. was connecting to the correct host+port, but with HTTP requests with `Host: localhost`
- (Setting `headers` > `Host` in config file had no effect, also not setting in yaml test files)
- Made no difference if config file was at a default location or indicated in command line with `--config`
- Trace output of ftw (`--trace`) did always show `Host: localhost`
- (Could not find any indication for the observed behavior in the source code, would seem to merge headers as documented)

(As a workaround in our case, because the Envoy instance to test was in Kubernetes, we configured the ingress to send requests to `localhost` to the Envoy instance to test, i.e. no urgency of any sort on our side...)

**Comment by theseion** [comment]
Thanks for the report @usp-ast. I'll have to take a look. It sounds to me like you're not testing locally, which means go-ftw wouldn't have access to the logs anyway. Are you using cloud mode?

**Comment by usp-ast** [comment]
Thanks for the feedback @theseion. No, we are not using cloud mode, we are piping the Envoy log via `kubectl` to a local file in parallel to running `ftw` (and that approach is working fine). Boiled down like this:

```
touch /path/to/envoy.log
kubectl -n <mynamespace> logs --follow pods/<mypod> >/path/to/envoy.log &
ftw run --config /path/to/ftw.yaml --dir /path/to/crs/test/dir --time
```

The config file looks like this:

```yaml
logfile: /path/to/envoy.log
mode: "default"
logmarkerheadername: X-CRS-Test
maxmarkerretries: 10
testoverride:
  input:
    dest_addr: <hostname>
    port: 8080
    # unfortunately had no effect on host header in practice (Jan 2025), hence ingress workaround instead
    #headers:
      #host: <hostname>
  ignore:
    # Envoy not compatible tests
    '911100-5': 'Invalid HTTP method. Rejected by Envoy with Error 400'
    ... all from https://github.com/mosn/envoy-go-waf/blob/main/ftw/ftw.yml
    '934120-39': 'Rule 934120 partially detected. With HTTP/1.1 Envoy return 400. With HTTP/2 Enclosed alphanumerics not detected. Coraza Side'
```

**Comment by theseion** [comment]
Setting the `Host` header in a test definitely works. Are you talking about the marker requests? Those target `localhost`, indeed. However, we just recently implemented exactly what you probably need. There is a new setting called `VirtualHostMode` which you can set to `true` to make marker request use the same `Host` header as the test requests:

```yaml
tests:
  - test_id: 1
    stages:
      - input:
        virtual_host_mode: true
```

We don't support setting it via overrides at the moment though. The new setting is part of [v1.2.0](https://github.com/coreruleset/go-ftw/releases/tag/v1.2.0). Let me know if that works for you and I can implement support for overrides as well.

**Comment by usp-ast** [comment]
What I observed was slightly different from what you described:

When setting `virtual_host_mode: true` at testoverrides/input, NOT setting `host` at testoverrides/input/headers and setting the desired host header in the test yaml, was using `Host: localhost` for all requests (marker and non-marker requests, both according to go-ftw trace log and `X-Forwarded-Host` header in the test Envoy after the ingress Envoy).

When setting `virtual_host_mode: true` and also setting `host` at testoverrides/input/headers to the desired host and setting the host header in the test yaml, was using the desired host header for non-marker requests (and still "Host: localhost" for marker requests, the ones with a `X-CRS-Test` header).

When setting `virtual_host_mode: true` and also setting `host` at testoverrides/input/headers to the desired host and leaving the host header in the test yaml at `localhost`, was using the desired host header for non-marker requests (and still "Host: localhost" for marker requests).

(Still using 1.2.0 as mentioned in the original description.)

**Comment by theseion** [comment]
Thanks for the clarification. I'll look into that.

**Comment by theseion** [comment]
I cannot reproduce your issue. Using the latest version of go-ftw and the following test I get these trace logs, which clearly show that the `Host` header is set to `foo` in all cases:

```yaml
  - test_id: 8
    desc: Method is not allowed by policy (911100) from old modsec regressions
    stages:
      - input:
          dest_addr: 127.0.0.1
          virtual_host_mode: true
          headers:
            Accept: text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5
            Accept-Encoding: gzip,deflate
            Accept-Language: en-us,en;q=0.5
            Host: foo
            Keep-Alive: '300'
            Proxy-Connection: keep-alive
            User-Agent: "OWASP CRS test agent"
          method: SUBSCRIBE
          port: 80
          uri: "/subscribe"
          version: HTTP/1.0
        output:
          log:
            expect_ids: [911100]
```

```
🛠️ Starting tests!
🚀 Running go-ftw!
[90m7:55AM[0m DBG Applying overrides for engine 'ModSecurity v2', platform 'httpd'
[90m7:55AM[0m [34mTRC[0m no override found for rule 911100
[90m7:55AM[0m [34mTRC[0m Writing header: Accept: */*

[90m7:55AM[0m [34mTRC[0m Writing header: Connection: close

[90m7:55AM[0m [34mTRC[0m Writing header: Host: foo

[90m7:55AM[0m [34mTRC[0m Writing header: User-Agent: go-ftw test agent

[90m7:55AM[0m [34mTRC[0m Writing header: X-CRS-Test: 6b2d6b3f-fca8-4e94-a318-daa6f3a0de29

[90m7:55AM[0m DBG ftw/http: sending data:
GET /status/200 HTTP/1.1
Accept: */*
Connection: close
Host: foo
User-Agent: go-ftw test agent
X-CRS-Test: 6b2d6b3f-fca8-4e94-a318-daa6f3a0de29



[90m7:55AM[0m [34mTRC[0m ftw/http: sending data
[90m7:55AM[0m [34mTRC[0m ftw/http: receiving data
[90m7:55AM[0m DBG ftw/http: received data - "HTTP/1.1 200 OK\r\nDate: Wed, 12 Feb 2025 06:55:26 GMT\r\nServer: Apache\r\nContent-Length: 0\r\nConnection: close\r\n\r\n"
[90m7:55AM[0m [34mTRC[0m Writing header: Accept: text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5

[90m7:55AM[0m [34mTRC[0m Writing header: Accept-Encoding: gzip,deflate

[90m7:55AM[0m [34mTRC[0m Writing header: Accept-Language: en-us,en;q=0.5

[90m7:55AM[0m [34mTRC[0m Writing header: Connection: close

[90m7:55AM[0m [34mTRC[0m Writing header: Host: foo

[90m7:55AM[0m [34mTRC[0m Writing header: Keep-Alive: 300

[90m7:55AM[0m [34mTRC[0m Writing header: Proxy-Connection: keep-alive

[90m7:55AM[0m [34mTRC[0m Writing header: User-Agent: OWASP CRS test agent

[90m7:55AM[0m DBG ftw/http: sending data:
SUBSCRIBE /subscribe HTTP/1.0
Accept: text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5
Accept-Encoding: gzip,deflate
Accept-Language: en-us,en;q=0.5
Connection: close
Host: foo
Keep-Alive: 300
Proxy-Connection: keep-alive
User-Agent: OWASP CRS test agent



[90m7:55AM[0m [34mTRC[0m ftw/http: sending data
[90m7:55AM[0m [34mTRC[0m ftw/http: receiving data
[90m7:55AM[0m DBG ftw/http: received data - "HTTP/1.1 200 OK\r\nDate: Wed, 12 Feb 2025 06:55:26 GMT\r\nServer: Apache\r\nContent-Length: 0\r\nConnection: close\r\n\r\n"
[90m7:55AM[0m [34mTRC[0m Writing header: Accept: */*

[90m7:55AM[0m [34mTRC[0m Writing header: Connection: close

[90m7:55AM[0m [34mTRC[0m Writing header: Host: foo

[90m7:55AM[0m [34mTRC[0m Writing header: User-Agent: go-ftw test agent

[90m7:55AM[0m [34mTRC[0m Writing header: X-CRS-Test: 6b2d6b3f-fca8-4e94-a318-daa6f3a0de29

[90m7:55AM[0m DBG ftw/http: sending data:
GET /status/200 HTTP/1.1
Accept: */*
Connection: close
Host: foo
User-Agent: go-ftw test agent
X-CRS-Test: 6b2d6b3f-fca8-4e94-a318-daa6f3a0de29



[90m7:55AM[0m [34mTRC[0m ftw/http: sending data
[90m7:55AM[0m [34mTRC[0m ftw/http: receiving data
[90m7:55AM[0m DBG ftw/http: received data - "HTTP/1.1 200 OK\r\nDate: Wed, 12 Feb 2025 06:55:26 GMT\r\nServer: Apache\r\nContent-Length: 0\r\nConnection: close\r\n\r\n"
[90m7:55AM[0m DBG [1m../../../go/pkg/mod/github.com/coreruleset/go-ftw@v1.2.0/check/error.go:17[0m[36m >[0m Error expected: false. Found: -
[90m7:55AM[0m [34mTRC[0m ftw/waflog: Looking for any rule in ''
[90m7:55AM[0m [34mTRC[0m ftw/waflog: Looking for any rule in '[Wed Feb 12 06:55:26.848845 2025] [security2:error] [pid 35:tid 281472451408160] [client 192.168.65.1:51549] [client 192.168.65.1] ModSecurity: Warning. Unconditional match in SecAction. [file "/etc/modsecurity.d/owasp-crs/rules/RESPONSE-980-CORRELATION.conf"] [line "98"] [id "980170"] [msg "Anomaly Scores: (Inbound Scores: blocking=5, detection=5, per_pl=5-0-0-0, threshold=5) - (Outbound Scores: blocking=0, detection=0, per_pl=0-0-0-0, threshold=4) - (SQLI=0, XSS=0, RFI=0, LFI=0, RCE=0, PHPI=0, HTTP=0, SESS=0, COMBINED_SCORE=5)"] [ver "OWASP_CRS/4.12.0-dev"] [tag "modsecurity"] [tag "reporting"] [tag "OWASP_CRS"] [hostname "foo"] [uri "/subscribe"] [unique_id "Z6xF3u1xvCjPn3f9UVS6TwAAAAg"]'
[90m7:55AM[0m [34mTRC[0m ftw/waflog: Found '\[(?:id |\\?"id\\?":)\\?"(\d+)\\?"\]' at '[Wed Feb 12 06:55:26.848845 2025] [security2:error] [pid 35:tid 281472451408160] [client 192.168.65.1:51549] [client 192.168.65.1] ModSecurity: Warning. Unconditional match in SecAction. [file "/etc/modsecurity.d/owasp-crs/rules/RESPONSE-980-CORRELATION.conf"] [line "98"] [id "980170"] [msg "Anomaly Scores: (Inbound Scores: blocking=5, detection=5, per_pl=5-0-0-0, threshold=5) - (Outbound Scores: blocking=0, detection=0, per_pl=0-0-0-0, threshold=4) - (SQLI=0, XSS=0, RFI=0, LFI=0, RCE=0, PHPI=0, HTTP=0, SESS=0, COMBINED_SCORE=5)"] [ver "OWASP_CRS/4.12.0-dev"] [tag "modsecurity"] [tag "reporting"] [tag "OWASP_CRS"] [hostname "foo"] [uri "/subscribe"] [unique_id "Z6xF3u1xvCjPn3f9UVS6TwAAAAg"]'
[90m7:55AM[0m [34mTRC[0m ftw/waflog: Looking for any rule in '[Wed Feb 12 06:55:26.847031 2025] [security2:error] [pid 35:tid 281472451408160] [client 192.168.65.1:51549] [client 192.168.65.1] ModSecurity: Warning. Operator GE matched 5 at TX:blocking_inbound_anomaly_score. [file "/etc/modsecurity.d/owasp-crs/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "233"] [id "949110"] [msg "Inbound Anomaly Score Exceeded (Total Score: 5)"] [ver "OWASP_CRS/4.12.0-dev"] [tag "modsecurity"] [tag "anomaly-evaluation"] [tag "OWASP_CRS"] [hostname "foo"] [uri "/subscribe"] [unique_id "Z6xF3u1xvCjPn3f9UVS6TwAAAAg"]'
[90m7:55AM[0m [34mTRC[0m ftw/waflog: Found '\[(?:id |\\?"id\\?":)\\?"(\d+)\\?"\]' at '[Wed Feb 12 06:55:26.847031 2025] [security2:error] [pid 35:tid 281472451408160] [client 192.168.65.1:51549] [client 192.168.65.1] ModSecurity: Warning. Operator GE matched 5 at TX:blocking_inbound_anomaly_score. [file "/etc/modsecurity.d/owasp-crs/rules/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "233"] [id "949110"] [msg "Inbound Anomaly Score Exceeded (Total Score: 5)"] [ver "OWASP_CRS/4.12.0-dev"] [tag "modsecurity"] [tag "anomaly-evaluation"] [tag "OWASP_CRS"] [hostname "foo"] [uri "/subscribe"] [unique_id "Z6xF3u1xvCjPn3f9UVS6TwAAAAg"]'
[90m7:55AM[0m [34mTRC[0m ftw/waflog: Looking for any rule in '[Wed Feb 12 06:55:26.844977 2025] [security2:error] [pid 35:tid 281472451408160] [client 192.168.65.1:51549] [client 192.168.65.1] ModSecurity: Warning. Match of "within %{tx.allowed_methods}" against "REQUEST_METHOD" required. [file "/etc/modsecurity.d/owasp-crs/rules/REQUEST-911-METHOD-ENFORCEMENT.conf"] [line "44"] [id "911100"] [msg "Method is not allowed by policy"] [data "SUBSCRIBE"] [severity "CRITICAL"] [ver "OWASP_CRS/4.12.0-dev"] [tag "modsecurity"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/210/272/220/274"] [tag "PCI/12.1"] [hostname "foo"] [uri "/subscribe"] [unique_id "Z6xF3u1xvCjPn3f9UVS6TwAAAAg"]'
[90m7:55AM[0m [34mTRC[0m ftw/waflog: Found '\[(?:id |\\?"id\\?":)\\?"(\d+)\\?"\]' at '[Wed Feb 12 06:55:26.844977 2025] [security2:error] [pid 35:tid 281472451408160] [client 192.168.65.1:51549] [client 192.168.65.1] ModSecurity: Warning. Match of "within %{tx.allowed_methods}" against "REQUEST_METHOD" required. [file "/etc/modsecurity.d/owasp-crs/rules/REQUEST-911-METHOD-ENFORCEMENT.conf"] [line "44"] [id "911100"] [msg "Method is not allowed by policy"] [data "SUBSCRIBE"] [severity "CRITICAL"] [ver "OWASP_CRS/4.12.0-dev"] [tag "modsecurity"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/210/272/220/274"] [tag "PCI/12.1"] [hostname "foo"] [uri "/subscribe"] [unique_id "Z6xF3u1xvCjPn3f9UVS6TwAAAAg"]'
➕ run 3919 total tests in 13.697542ms
⏭ skipped 3918 tests
🎉 All tests successful!
```
