### ISSUE TITLE
cloud mode test always success

### ISSUE THREAD

**Issue by xu-xiang** [coreruleset/go-ftw#467]
In cloud mode, I found that whether it's a 200, 404, or 403 (intercepted) response, the test results are all considered successful. The expected behavior should be able to distinguish 202, 404, etc., as non-intercepted or allow customization of status codes.

```
./bin/ftw_mac run  -d regression/tests/ --config regression/cloud-test.yaml --debug  --include "946965" --show-failures-only
🛠️ Starting tests!
🚀 Running go-ftw!
5:55PM DBG Applying overrides for engine '', platform ''
5:55PM DBG ftw/http: sending data:
GET /xxxx HTTP/1.1
Accept: */*
Accept-Language: en
Connection: close
Host: 10.253.182.151
User-Agent: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.3319.102 Safari/537.36



5:55PM DBG ftw/http: received data - "HTTP/1.1 404 \r\nServer: cec slb\r\nDate: Fri, 07 Mar 2025 09:55:44 GMT\r\nContent-Type: text/html;charset=utf-8\r\nContent-Length: 1074\r\nConnection: close\r\nVary: Accept-Encoding\r\nContent-Language: en\r\n\r\n<!doctype html><html lang=\"en\"><head><title>HTTP Status 404 – Not Found</title><style type=\"text/css\">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 – Not Found</h1><hr class=\"line\" /><p><b>Type</b> Status Report</p><p><b>Message</b> /xxxx</p><p><b>Description</b> The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.</p><hr class=\"line\" /><h3>Apache Tomcat/8.5.19</h3></body></html>"
5:55PM DBG ../../../../../home/runner/work/go-ftw/go-ftw/check/error.go:17 > Error expected: false. Found: -
➕ run 3908 total tests in 107.47575ms
⏭ skipped 3907 tests
🎉 All tests successful!
```

**Comment by theseion** [comment]
Thanks @xu-xiang, we'll investigate. Which version of go-ftw are you running?

**Comment by theseion** [comment]
You can define the status code you expect using the `output.status` field. What does your test look like?

**Comment by xu-xiang** [comment]
1、ftw version 1.2.0

2、add output.status
```
ftw  run  --config regression/cloud-test.yaml --debug  --include "946965" --show-failures-only
```
```
meta:
    author: test
    description: test
rule_id: 946965
tests:
    - test_id: 1
      desc: test
      stages:
        - input:
            dest_addr: 127.0.0.1
            method: GET
            port: 80
            headers:
                Accept: '*/*'
                Accept-Encoding: gzip
                Accept-Language: en
                Connection: close
                Host: 127.0.0.1
                User-Agent: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.3319.102 Safari/537.36
            uri: /boafrm/formWlanRedirect?redirect-url=http://interact.sh&wlan_id=1
            version: HTTP/1.1
          output:
            log:
                expect_ids: [946965]
            status: 200

```
result
```
➕ run 3927 total tests in 116.078ms
⏭ skipped 3926 tests
🎉 All tests successful!
```

**Comment by theseion** [comment]
When I run your test it doesn't fail, as expected. The web server returns 200. When I modify the expected status code to something else, e.g., 201, the test fails, as expected.

Not sure what you are expecting to see...

**Comment by xu-xiang** [comment]
All rules that require cloud mode testing need to be modified to include something like status: 403 (expecting a 403 block; if not blocked, the test is considered a failure)? In cloud mode, the expected status code cannot be directly specified via command-line parameters to determine test success, making it cumbersome to modify all rules?

**Comment by xu-xiang** [comment]
Is it possible to use test_overrides to change the output of all rules to 401 instead of modifying each rule individually?

**Comment by xu-xiang** [comment]
But if --overrides is not used, cloud-test also supports certain override configurations, but the configuration does not seem to support overriding the output field
```
./bin/ftw run  --config regression/cloud-test.yaml --debug  --include "946965"
```


```
mode: 'cloud'
testoverride:
  input:   # work
    dest_addr: "127.0.0.1"  # WAF IP & Port
    port: 80
    headers:
      Host: "127.0.0.1"
  output:
    status:
      401   # not work
```
