### ISSUE TITLE
ftw consumes too much memory

### ISSUE THREAD

**Issue by xu-xiang** [coreruleset/go-ftw#496]
When running the 44M test cases, the ftw process on macOS occupies 20G of memory

**Comment by fzipi** [comment]
🤔 QQ: can you sum the total contents of the files in bytes?

**Comment by xu-xiang** [comment]
There is only one YAML file

**Comment by fzipi** [comment]
Size?

**Comment by xu-xiang** [comment]
```
➜  ~ ls -lh /tmp/false_positives/false_positives.yaml
-rw-r--r--  1 Library  staff    44M  5  8 18:42 /tmp/false_positives/false_positives.yaml
➜  ~
```

**Comment by fzipi** [comment]
Let's see if we can reproduce somehow, and try to find where the memory might be going.

**Comment by xu-xiang** [comment]
Thanks.

**Comment by xu-xiang** [comment]
Test case example:
```
    - test_id: 2
      desc: ""
      stages:
        - input:
            dest_addr: 127.0.0.1
            method: POST
            port: 80
            headers:
                Accept: '*/*'
                Accept-Encoding: gzip, deflate
                Accept-Language: zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7
                Content-Length: "219"
                Content-Type: text/plain;charset=UTF-8
                Host: ams.game.qq.com
                Origin: https://pvp.qq.com
                Referer: https://pvp.qq.com/
                Sec-Ch-Ua: '"Not.A/Brand";v="8", "Chromium";v="114", "Google Chrome";v="114"'
                Sec-Ch-Ua-Mobile: ?0
                Sec-Ch-Ua-Platform: '"Windows"'
                Sec-Fetch-Dest: empty
                Sec-Fetch-Mode: cors
                Sec-Fetch-Site: same-site
                User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
            uri: /log?sCloudApiName=atm
            version: HTTP/1.1
            data: |-
                {"cgi":"https://pvp.qq.com/","errormsg":"访问成功","fromappid":38,"frommoduletype":4,"toappid":38,"tomoduletype":3,"tointer":1,"businesstype":"pvp","struserid":"","serialtime":1688379786,"result":0,"toreturncode":0}
          output:
            log:
                no_match_regex: \[id "\d+"
```
