### ISSUE TITLE
tls: failed to verify certificate: x509

### ISSUE THREAD

**Issue by xu-xiang** [coreruleset/go-ftw#503]
I used the --wait-for-insecure-skip-tls-verify parameter, but I still got a certificate error
```
./bin/ftw run -d regression/tests/ --config regression/cloud-test.yaml --debug  --include "^9994026" --wait-for-insecure-skip-tls-verify


🛠️ Starting tests!
🚀 Running go-ftw!
3:10PM DBG Applying overrides for engine '', platform ''
👉 executing tests in file 
        running 9994026-4026: Error: can't connect to destination &{DestAddr:10.0.0.5 Port:443 Protocol:https}: tls: failed to verify certificate: x509: certificate signed by unknown authority 
```

cloud-test.yaml
```
mode: 'cloud'
testoverride:
  input:
    dest_addr: "10.0.0.5"
    port: 443
    protocol: https
    headers:
      Host: "test.waf.com"
  output:
    expect_error: true
```
